src/Skoruba.Duende.IdentityServer.Admin.UI/Areas/AdminUI/Controllers/ConfigurationController.cs
// Copyright (c) Jan Škoruba. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.

using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Dtos.Configuration;
using Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Helpers;
using Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Services.Interfaces;
using Skoruba.Duende.IdentityServer.Admin.UI.Configuration.Constants;
using Skoruba.Duende.IdentityServer.Admin.UI.ExceptionHandling;
using Skoruba.Duende.IdentityServer.Admin.UI.Helpers;

namespace Skoruba.Duende.IdentityServer.Admin.UI.Areas.AdminUI.Controllers
{
    [Authorize(Policy = AuthorizationConsts.AdministrationPolicy)]
    [TypeFilter(typeof(ControllerExceptionFilterAttribute))]
    [Area(CommonConsts.AdminUIArea)]
    public class ConfigurationController : BaseController
    {
        private readonly IIdentityResourceService _identityResourceService;
        private readonly IApiResourceService _apiResourceService;
        private readonly IClientService _clientService;
        private readonly IStringLocalizer<ConfigurationController> _localizer;
        private readonly IApiScopeService _apiScopeService;

        public ConfigurationController(IIdentityResourceService identityResourceService,
            IApiResourceService apiResourceService,
            IClientService clientService,
            IStringLocalizer<ConfigurationController> localizer,
            ILogger<ConfigurationController> logger,
            IApiScopeService apiScopeService)
            : base(logger)
        {
            _identityResourceService = identityResourceService;
            _apiResourceService = apiResourceService;
            _clientService = clientService;
            _localizer = localizer;
            _apiScopeService = apiScopeService;
        }

        public async Task<IActionResult> Client(string id)
        {
            if (id.IsNotPresentedValidNumber())
            {
                return NotFound();
            }

            if (id == default)
            {
                var clientDto = _clientService.BuildClientViewModel();
                return View(clientDto);
            }

            int.TryParse(id, out var clientId);
            var client = await _clientService.GetClientAsync(clientId);
            client = _clientService.BuildClientViewModel(client);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Client(ClientDto client)
        {
            client = _clientService.BuildClientViewModel(client);

            if (!ModelState.IsValid)
            {
                return View(client);
            }

            //Add new client
            if (client.Id == 0)
            {
                var clientId = await _clientService.AddClientAsync(client);
                SuccessNotification(string.Format(_localizer["SuccessAddClient"], client.ClientId), _localizer["SuccessTitle"]);

                return RedirectToAction(nameof(Client), new { Id = clientId });
            }

            //Update client
            await _clientService.UpdateClientAsync(client);
            SuccessNotification(string.Format(_localizer["SuccessUpdateClient"], client.ClientId), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Client), new { client.Id });
        }

        [HttpGet]
        public async Task<IActionResult> ClientClone(int id)
        {
            if (id == 0) return NotFound();

            var clientDto = await _clientService.GetClientAsync(id);
            var client = _clientService.BuildClientCloneViewModel(id, clientDto);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientClone(ClientCloneDto client)
        {
            if (!ModelState.IsValid)
            {
                return View(client);
            }

            var newClientId = await _clientService.CloneClientAsync(client);
            SuccessNotification(string.Format(_localizer["SuccessClientClone"], client.ClientId), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Client), new { Id = newClientId });
        }

        [HttpGet]
        public async Task<IActionResult> ClientDelete(int id)
        {
            if (id == 0) return NotFound();

            var client = await _clientService.GetClientAsync(id);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientDelete(ClientDto client)
        {
            await _clientService.RemoveClientAsync(client);

            SuccessNotification(_localizer["SuccessClientDelete"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Clients));
        }

        [HttpGet]
        public async Task<IActionResult> ClientClaims(int id, int? page)
        {
            if (id == 0) return NotFound();

            var claims = await _clientService.GetClientClaimsAsync(id, page ?? 1);

            return View(claims);
        }

        [HttpGet]
        public async Task<IActionResult> ClientProperties(int id, int? page)
        {
            if (id == 0) return NotFound();

            var properties = await _clientService.GetClientPropertiesAsync(id, page ?? 1);

            return View(properties);
        }

        [HttpGet]
        public async Task<IActionResult> ApiResourceProperties(int id, int? page)
        {
            if (id == 0) return NotFound();

            var properties = await _apiResourceService.GetApiResourcePropertiesAsync(id, page ?? 1);

            return View(properties);
        }

        [HttpGet]
        public async Task<IActionResult> ApiScopeProperties(int id, int? page)
        {
            if (id == 0) return NotFound();

            var properties = await _apiScopeService.GetApiScopePropertiesAsync(id, page ?? 1);

            return View(properties);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ApiScopeProperties(ApiScopePropertiesDto apiScopeProperty)
        {
            if (!ModelState.IsValid)
            {
                return View(apiScopeProperty);
            }

            await _apiScopeService.AddApiScopePropertyAsync(apiScopeProperty);
            SuccessNotification(string.Format(_localizer["SuccessAddApiScopeProperty"], apiScopeProperty.Key, apiScopeProperty.ApiScopeName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ApiScopeProperties), new { Id = apiScopeProperty.ApiScopeId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ApiResourceProperties(ApiResourcePropertiesDto apiResourceProperty)
        {
            if (!ModelState.IsValid)
            {
                return View(apiResourceProperty);
            }

            await _apiResourceService.AddApiResourcePropertyAsync(apiResourceProperty);
            SuccessNotification(string.Format(_localizer["SuccessAddApiResourceProperty"], apiResourceProperty.Key, apiResourceProperty.ApiResourceName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ApiResourceProperties), new { Id = apiResourceProperty.ApiResourceId });
        }

        [HttpGet]
        public async Task<IActionResult> IdentityResourceProperties(int id, int? page)
        {
            if (id == 0) return NotFound();

            var properties = await _identityResourceService.GetIdentityResourcePropertiesAsync(id, page ?? 1);

            return View(properties);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> IdentityResourceProperties(IdentityResourcePropertiesDto identityResourceProperty)
        {
            if (!ModelState.IsValid)
            {
                return View(identityResourceProperty);
            }

            await _identityResourceService.AddIdentityResourcePropertyAsync(identityResourceProperty);
            SuccessNotification(string.Format(_localizer["SuccessAddIdentityResourceProperty"], identityResourceProperty.Value, identityResourceProperty.IdentityResourceName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(IdentityResourceProperties), new { Id = identityResourceProperty.IdentityResourceId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientProperties(ClientPropertiesDto clientProperty)
        {
            if (!ModelState.IsValid)
            {
                return View(clientProperty);
            }

            await _clientService.AddClientPropertyAsync(clientProperty);
            SuccessNotification(string.Format(_localizer["SuccessAddClientProperty"], clientProperty.ClientId, clientProperty.ClientName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientProperties), new { Id = clientProperty.ClientId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientClaims(ClientClaimsDto clientClaim)
        {
            if (!ModelState.IsValid)
            {
                return View(clientClaim);
            }

            await _clientService.AddClientClaimAsync(clientClaim);
            SuccessNotification(string.Format(_localizer["SuccessAddClientClaim"], clientClaim.Value, clientClaim.ClientName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientClaims), new { Id = clientClaim.ClientId });
        }

        [HttpGet]
        public async Task<IActionResult> ClientClaimDelete(int id)
        {
            if (id == 0) return NotFound();

src/Skoruba.Duende.IdentityServer.Admin.UI/Areas/AdminUI/Views/Configuration/ApiResourceDelete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.Duende.IdentityServer.Admin.UI.Configuration.Constants
@model Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Dtos.Configuration.ApiResourceDto
@inject IViewLocalizer Localizer

@{
	ViewBag.Title = Localizer["PageTitle"];
	Layout = "_Layout";
}	

<div class="row">
	<div class="col-12">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiResources">@Localizer["NavigationApiResources"]</a></li>
				<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiResource" asp-route-id="@Model.Id">@Model.Name</a></li>
				<li class="breadcrumb-item active" aria-current="page">@Localizer["PageTitle"]</li>
			</ol>
		</nav>
	</div>

	<div class="col-12">
		<h2>@Localizer["PageTitle"]</h2>
	</div>
</div>

<form asp-area="@CommonConsts.AdminUIArea" asp-action="ApiResourceDelete" method="post" id="api-resource-form">

	<!--Hidden -->
	<input type="hidden" asp-for="Id" />

	<div class="card mt-3">
		<h5 class="card-header">@Localizer["PanelTitle"]</h5>
		<div class="card-body">

			<!--Input - text -->
			<div class="form-group row">
				<label asp-for="Name" class="col-sm-3 col-form-label">
					@await Html.PartialAsync("ApiResource/Section/Label", "Name")
				</label>
				<div class="col-sm-9">
					<input type="text" class="form-control" disabled="disabled" asp-for="Name">
				</div>
			</div>

			<!--Button-->
			<div class="form-group row">
				<label class="col-sm-3 col-form-label">
				</label>
				<div class="col-sm-9">
					<button type="submit" class="btn btn-danger">@Localizer["ButtonDeleteApiResource"]</button>
				</div>
			</div>
		</div>
	</div>
</form>

src/Skoruba.Duende.IdentityServer.Admin.UI/Areas/AdminUI/Views/Configuration/ApiResourcePropertyDelete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.Duende.IdentityServer.Admin.UI.Configuration.Constants
@model Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Dtos.Configuration.ApiResourcePropertiesDto
@inject IViewLocalizer Localizer

@{
	ViewBag.Title = Localizer["PageTitle"];
	Layout = "_Layout";
}

<form asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiResourcePropertyDelete" Method="post">
	<div class="row">

		<div class="col-12">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiResources">@Localizer["NavigationApiResources"]</a></li>
					<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiResource" asp-route-id="@Model.ApiResourceId">@Model.ApiResourceName</a></li>
					<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiResourceProperties" asp-route-id="@Model.ApiResourceId">@Localizer["NavigationApiResourceProperties"]</a></li>
					<li class="breadcrumb-item active" aria-current="page">@Localizer["PageTitle"]</li>
				</ol>
			</nav>
		</div>

		<div class="col-md-12">
			<h3>@Localizer["PageTitle"]</h3>
			
			<!--Hidden -->
			<input type="hidden" asp-for="ApiResourceId" />
			<input type="hidden" asp-for="ApiResourcePropertyId" />

			<div class="card mt-3">
				<h5 class="card-header">@Localizer["PanelTitle"]</h5>
				<div class="card-body">
					<!--Input - text -->
					<div class="form-group row">
						<label asp-for="Key" class="col-sm-3 col-form-label">
							@await Html.PartialAsync("ApiResource/Section/Label", "PropertyKey")
						</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" disabled="disabled" asp-for="Key">
						</div>
					</div>

					<!--Input - text -->
					<div class="form-group row">
						<label asp-for="Value" class="col-sm-3 col-form-label">
							@await Html.PartialAsync("ApiResource/Section/Label", "PropertyValue")
						</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" disabled="disabled" asp-for="Value">
						</div>
					</div>

					<!--Button-->
					<div class="form-group row">
						<label class="col-sm-3 col-form-label">
						</label>
						<div class="col-sm-9">
							<button type="submit" class="btn btn-danger">@Localizer["ButtonDeleteProperty"]</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

src/Skoruba.Duende.IdentityServer.Admin.UI/Areas/AdminUI/Views/Configuration/ApiScopeDelete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.Duende.IdentityServer.Admin.UI.Configuration.Constants
@model Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Dtos.Configuration.ApiScopeDto
@inject IViewLocalizer Localizer

@{
	ViewBag.Title = Localizer["PageTitle"];
	Layout = "_Layout";
}

<div class="row">
	<div class="col-12">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScopes">@Localizer["NavigationApiScopes"]</a></li>
				<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScopes" asp-route-scope="@Model.Id">@Model.Name</a></li>
				<li class="breadcrumb-item active" aria-current="page">@Localizer["PageTitle"]</li>
			</ol>
		</nav>
	</div>

	<div class="col-12">
		<h2>@Localizer["PageTitle"]</h2>
	</div>
</div>

<form asp-area="@CommonConsts.AdminUIArea" asp-action="ApiScopeDelete" method="post">

	<!--Hidden -->
	<input type="hidden" asp-for="Id" />
	
	<div class="card mt-3">
		<h5 class="card-header">@Localizer["PanelTitle"]</h5>
		<div class="card-body">

			<!--Input - text -->
			<div class="form-group row">
				<label asp-for="Name" class="col-sm-3 col-form-label">
					@await Html.PartialAsync("ApiResource/Section/Label", "Name")
				</label>
				<div class="col-sm-9">
					<input type="text" class="form-control" disabled="disabled" asp-for="Name">
				</div>
			</div>

			<!--Button-->
			<div class="form-group row">
				<label class="col-sm-3 col-form-label">
				</label>
				<div class="col-sm-9">
					<button type="submit" class="btn btn-danger">@Localizer["ButtonDeleteApiScope"]</button>
				</div>
			</div>
		</div>
	</div>

</form>

src/Skoruba.Duende.IdentityServer.Admin.UI/Areas/AdminUI/Views/Configuration/ApiScopeProperties.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Shared.Dtos.Common
@using Skoruba.Duende.IdentityServer.Admin.UI.Configuration.Constants
@model Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Dtos.Configuration.ApiScopePropertiesDto
@inject IViewLocalizer Localizer

@{
	ViewBag.Title = Localizer["PageTitle"];
	Layout = "_Layout";
}

<form asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScopeProperties" Method="post">
	<div class="row">

		<div class="col-12">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScopes">@Localizer["NavigationApiScopes"]</a></li>
					<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScope" asp-route-id="@Model.ApiScopeId">@Model.ApiScopeName</a></li>
					<li class="breadcrumb-item active" aria-current="page">@Localizer["PageTitle"]</li>
				</ol>
			</nav>
		</div>

		<div class="col-md-12">

			<h3>@Localizer["PageTitle"]</h3>

			<div asp-validation-summary="All" class="text-danger"></div>

			<!--Hidden -->
			<input type="hidden" asp-for="ApiScopeId" />

			<!--Hidden -->
			<input type="hidden" asp-for="ApiScopeName" />

			<div class="card mt-3">
				<h5 class="card-header">@Localizer["PageSubTitle"]</h5>
				<div class="card-body">

					<!--Input - text -->
					<div class="form-group row">
						<label asp-for="Key" class="col-sm-3 col-form-label">
							@await Html.PartialAsync("ApiScope/Section/Label", "PropertyKey")
						</label>
						<div class="col-sm-9">
							<input type="text" required class="form-control" asp-for="Key">
							<span asp-validation-for="Key" class="text-danger"></span>
						</div>
					</div>

					<!--Input - text -->
					<div class="form-group row">
						<label asp-for="Value" class="col-sm-3 col-form-label">
							@await Html.PartialAsync("ApiScope/Section/Label", "PropertyValue")
						</label>
						<div class="col-sm-9">
							<input type="text" required class="form-control" asp-for="Value">
							<span asp-validation-for="Value" class="text-danger"></span>
						</div>
					</div>

					<!--Button-->
					<div class="form-group row">
						<label class="col-sm-3 col-form-label">
						</label>
						<div class="col-sm-9">
							<button type="submit" class="btn btn-primary">@Localizer["ButtonAddApiScopeProperty"]</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

<div class="row">
	<div class="col-md-12">
		<div class="card mt-3">
			<h5 class="card-header">@Localizer["PageTitle"]</h5>
			<div class="card-body">
				<div class="row table-responsive">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>@Localizer["TableKey"]</th>
								<th>@Localizer["TableValue"]</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							@foreach (var apiResourceProperty in Model.ApiScopeProperties)
							{
								<tr>
									<td>@apiResourceProperty.Key</td>
									<td>@apiResourceProperty.Value</td>
									<td><a asp-area="@CommonConsts.AdminUIArea" asp-action="ApiScopePropertyDelete" asp-route-id="@apiResourceProperty.Id" class="btn btn-danger">@Localizer["TableDelete"]</a></td>
								</tr>
							}
						</tbody>
					</table>
				</div>

				<div class="row">
					<div class="col-12">
						@await Html.PartialAsync("Common/Pager", new Pager { Action = "ApiResourceProperties", PageSize = Model.PageSize, TotalCount = Model.TotalCount })
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

src/Skoruba.Duende.IdentityServer.Admin.UI/Areas/AdminUI/Views/Configuration/ApiScopePropertyDelete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.Duende.IdentityServer.Admin.UI.Configuration.Constants
@model Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Dtos.Configuration.ApiScopePropertiesDto
@inject IViewLocalizer Localizer

@{
	ViewBag.Title = Localizer["PageTitle"];
	Layout = "_Layout";
}

<form asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScopePropertyDelete" Method="post">
	<div class="row">

		<div class="col-12">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScopes">@Localizer["NavigationApiScopes"]</a></li>
					<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScope" asp-route-id="@Model.ApiScopeId">@Model.ApiScopeName</a></li>
					<li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="ApiScopeProperties" asp-route-id="@Model.ApiScopeId">@Localizer["NavigationApiScopeProperties"]</a></li>
					<li class="breadcrumb-item active" aria-current="page">@Localizer["PageTitle"]</li>
				</ol>
			</nav>
		</div>

		<div class="col-md-12">
			<h3>@Localizer["PageTitle"]</h3>
			
			<!--Hidden -->
			<input type="hidden" asp-for="ApiScopeId" />
			<input type="hidden" asp-for="ApiScopePropertyId" />

			<div class="card mt-3">
				<h5 class="card-header">@Localizer["PageTitle"]</h5>
				<div class="card-body">
					<!--Input - text -->
					<div class="form-group row">
						<label asp-for="Key" class="col-sm-3 col-form-label">
							@await Html.PartialAsync("ApiScope/Section/Label", "PropertyKey")
						</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" disabled="disabled" asp-for="Key">
						</div>
					</div>

					<!--Input - text -->
					<div class="form-group row">
						<label asp-for="Value" class="col-sm-3 col-form-label">
							@await Html.PartialAsync("ApiScope/Section/Label", "PropertyValue")
						</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" disabled="disabled" asp-for="Value">
						</div>
					</div>

					<!--Button-->
					<div class="form-group row">
						<label class="col-sm-3 col-form-label">
						</label>
						<div class="col-sm-9">
							<button type="submit" class="btn btn-danger">@Localizer["ButtonDeleteApiScopeProperty"]</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

src/Skoruba.Duende.IdentityServer.Admin.UI/Areas/AdminUI/Views/Configuration/Client.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.Duende.IdentityServer.Admin.UI.Configuration.Constants
@model Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Dtos.Configuration.ClientDto
@inject IViewLocalizer Localizer

@{
    ViewBag.Title = Localizer["PageTitle"];
    Layout = "_Layout";
}

<form asp-area="@CommonConsts.AdminUIArea" id="client-form" asp-controller="Configuration" asp-action="Client" Method="post">

    <div class="row">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-area="@CommonConsts.AdminUIArea" asp-controller="Configuration" asp-action="Clients">@Localizer["NavigationClients"]</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@Model.ClientName (@Model.ClientId)</li>
                </ol>
            </nav>
        </div>

        @if (Model.Id != 0)
        {
            <div class="col-12">
                <h2>@Localizer["Title"] @Model.ClientName</h2>
            </div>
        }

        <div class="col-12">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
    </div>

    @if (Model.Id != 0)
    {
        @await Html.PartialAsync("Client/Section/ActionButtons")
    }

    @await Html.PartialAsync("Client/Settings")
    @await Html.PartialAsync("Client/Section/ActionButtons")
</form>

@section scripts
	{
    <script>
        $(function () {
            //Disable enter for this form
            FormMvc.disableEnter($('#client-form'));

            //Radio image
            $("label.radio-img>img").click(function () {
                $(this).parent().find("input:radio").click();
            });
        });
    </script>
}